config-version = 2

start-at-login = true
after-startup-command = []

# NOTE: for some reason fails the reload
# auto-reload-config = false

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

persistent-workspaces = ["1", "2", "3", "4", "0"]

on-mode-changed = []

[key-mapping]
    preset = 'qwerty'

[workspace-to-monitor-force-assignment]
    1 = 1 
    2 = 1 
    3 = 1 
    4 = 1
    0 = 2

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

# List of all possible values: https://nikitabobko.github.io/AeroSpace/guide#default-config
[mode.main.binding]
    alt-period = 'layout tiles horizontal vertical' # azerty : 
    alt-comma = 'layout accordion horizontal vertical' # azerty ;

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-ctrl-h = 'move left'
    alt-ctrl-j = 'move down'
    alt-ctrl-k = 'move up'
    alt-ctrl-l = 'move right'

    alt-equal = 'resize smart -50' # azerty - 
    alt-slash = 'resize smart +50' # azerty =

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-0 = 'workspace 0'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-0 = 'move-node-to-workspace 0'

    alt-a = 'focus-monitor next'
    alt-shift-a = 'move-node-to-monitor next'

    alt-tab = 'workspace-back-and-forth'

    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']
